mytodoapp:
  name: "mytodoapp-helm"
  image: "thsre/mytodoapp"
  replicas: "3"
  ports:
    - port: 3000
      targetPort: 3000
      name: "mytodoapp"
      servicetype: "NodePort"
      NodePort: 32500
  labels:
    app: "mytodoapp"
    env: "labs"
    live: "true"
  service:
    name: "mytodoapp-svc"
    type: "ClusterIP"
    port: 3000
    targePort: 3000
  resources:
   requests:
     memory: "64Mi"
     cpu: "250m"
   limits:
     memory: "128Mi"
     cpu: "500m"
redis:
  name: "redis-helm"
  image: "redis"
  replicas: "1"
  port: 
  labels:
    app: "redis"
  service:
    name: "redis-svc"
    type: "ClusterIP"
    port: 6379
    targePort: 6379
  resources:
   requests:
     memory: "64Mi"
     cpu: "250m"
   limits:
     memory: "128Mi"
     cpu: "500m"